<?xml version="1.0" encoding="utf-8"?><Database Name="FjutOrgDept" Class="DataClassesDataContext" Serialization="Unidirectional" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=PC201309101713\WJS;Initial Catalog=FjutOrgDept;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="FjutOrgDeptConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ViewPosApl" Member="ViewPosApl">
    <Type Name="ViewPosApl">
      <Column Name="F_ID" Type="System.String" DbType="NChar(36) NOT NULL" CanBeNull="false" />
      <Column Name="F_UserID" Type="System.String" DbType="NChar(36) NOT NULL" CanBeNull="false" />
      <Column Name="F_StaffID" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="F_appliedDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="F_status" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="F_statusEnum" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="F_pos1" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="F_pos2" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="F_pos3" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="F_userName" Type="System.String" DbType="VarChar(32)" CanBeNull="true" />
      <Column Name="F_realName" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="F_sexual" Type="System.String" DbType="Char(2)" CanBeNull="true" />
      <Column Name="F_workDept" Type="System.String" DbType="NVarChar(40)" CanBeNull="true" />
      <Column Name="F_highestDegree" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="F_highestEducation" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="F_nationality" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="F_birthday" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="F_position" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="F_title" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="F_Role" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="F_belongDeptID" Type="System.String" DbType="NChar(36)" CanBeNull="true" />
      <Column Name="F_nativeplace" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="F_party" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="F_highestGrduateSch" Type="System.String" DbType="NChar(30)" CanBeNull="true" />
      <Column Name="F_titleBeginDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="F_resume" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="F_rwdandpunishmt" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="F_reason" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="F_posID1" Type="System.String" DbType="NChar(36)" CanBeNull="true" />
      <Column Name="F_posID2" Type="System.String" DbType="NChar(36)" CanBeNull="true" />
      <Column Name="F_posID3" Type="System.String" DbType="NChar(36)" CanBeNull="true" />
      <Column Name="F_endDate1" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="F_endDate2" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="F_endDate3" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="F_posBeginDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="F_adminRanking" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="F_adminRkBeginDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ViewUserInDept" Member="ViewUserInDept">
    <Type Name="ViewUserInDept">
      <Column Name="F_ID" Type="System.String" DbType="Char(36) NOT NULL" CanBeNull="false" />
      <Column Name="用户名" Type="System.String" DbType="VarChar(32)" CanBeNull="true" />
      <Column Name="真实姓名" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="所属部门" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="用户身份" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="状态" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="姓别" Type="System.String" DbType="Char(2)" CanBeNull="true" />
      <Column Name="学位" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="学历" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ViewStaffInDept" Member="ViewStaffInDept">
    <Type Name="ViewStaffInDept">
      <Column Name="F_StaffID" Type="System.String" DbType="NChar(36) NOT NULL" CanBeNull="false" />
      <Column Name="F_UserID" Type="System.String" DbType="NChar(36)" CanBeNull="true" />
      <Column Name="用户名" Type="System.String" DbType="VarChar(32)" CanBeNull="true" />
      <Column Name="真实姓名" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="所属部门" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="状态" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="姓别" Type="System.String" DbType="Char(2)" CanBeNull="true" />
      <Column Name="学位" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="学历" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.DeptMent" Member="DeptMent">
    <Type Name="DeptMent">
      <Column Name="F_ID" Type="System.String" DbType="NChar(36) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="F_unitID" Type="System.String" DbType="Char(5)" CanBeNull="true" />
      <Column Name="F_status" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="F_name" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="F_type" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.[User]" Member="User">
    <Type Name="User">
      <Column Name="F_ID" Type="System.String" DbType="Char(36) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="F_userName" Type="System.String" DbType="VarChar(32)" CanBeNull="true" />
      <Column Name="F_pwd" Type="System.String" DbType="VarChar(32)" CanBeNull="true" />
      <Column Name="F_realName" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="F_sexual" Type="System.String" DbType="Char(2)" CanBeNull="true" />
      <Column Name="F_idType" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="F_idNumber" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="F_workDept" Type="System.String" DbType="NVarChar(40)" CanBeNull="true" />
      <Column Name="F_phone" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="F_mobile" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="F_highestDegree" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="F_highestEducation" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="F_nationality" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="F_birthday" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="F_position" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="F_title" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="F_freeAddress" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="F_phone2" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="F_fax" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="F_email" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="F_mostFamiliarSubject" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="F_familiarSubject1" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="F_familiarSubject2" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="F_Role" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="F_status" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="F_belongDeptID" Type="System.String" DbType="NChar(36)" CanBeNull="true" />
      <Column Name="F_bornplace" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="F_nativeplace" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="F_party" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="F_partyEntryDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="F_workBeginDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="F_highestGrduateSch" Type="System.String" DbType="NChar(30)" CanBeNull="true" />
      <Column Name="F_titleBeginDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="F_resume" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="F_rwdandpunishmt" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="F_lastModifyTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="F_posBeginDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="F_adminRanking" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="F_adminRkBeginDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.FamilyMember" Member="FamilyMember">
    <Type Name="FamilyMember">
      <Column Name="F_ID" Type="System.String" DbType="NChar(36) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="F_userID" Type="System.String" DbType="NChar(36)" CanBeNull="true" />
      <Column Name="F_familyMemName" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="F_familyMemBirthday" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="F_familyMemParty" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="F_familyMemWorkInfo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="F_familyMemAppelation" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Logger" Member="Logger">
    <Type Name="Logger">
      <Column Name="F_ID" Type="System.String" DbType="Char(36) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="F_userID" Type="System.String" DbType="Char(36)" CanBeNull="true" />
      <Column Name="F_ipAddr" Type="System.String" DbType="VarChar(32)" CanBeNull="true" />
      <Column Name="F_datetime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="F_content" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="F_type" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Patent" Member="Patent">
    <Type Name="Patent">
      <Column Name="F_ID" Type="System.String" DbType="Char(36) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="F_name" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="F_code" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="F_type" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="F_declareDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="F_userID" Type="System.String" DbType="Char(36)" CanBeNull="true" />
      <Column Name="F_appliedDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="F_status" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="F_projectID" Type="System.String" DbType="Char(36)" CanBeNull="true" />
      <Column Name="F_applyCode" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.PosApplicant" Member="PosApplicant">
    <Type Name="PosApplicant">
      <Column Name="F_ID" Type="System.String" DbType="NChar(36) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="F_UserID" Type="System.String" DbType="NChar(36) NOT NULL" CanBeNull="false" />
      <Column Name="F_StaffID" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="F_appliedDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="F_status" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="F_statusEnum" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="F_pos1" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="F_pos2" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="F_pos3" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="F_reason" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="F_posID1" Type="System.String" DbType="NChar(36)" CanBeNull="true" />
      <Column Name="F_posID2" Type="System.String" DbType="NChar(36)" CanBeNull="true" />
      <Column Name="F_posID3" Type="System.String" DbType="NChar(36)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Schedule" Member="Schedule">
    <Type Name="Schedule">
      <Column Name="F_ID" Type="System.String" DbType="Char(36) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="F_beginDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="F_endDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="F_content" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="F_projectID" Type="System.String" DbType="Char(36)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Staff" Member="Staff">
    <Type Name="Staff">
      <Column Name="F_StaffID" Type="System.String" DbType="NChar(36) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="F_UserID" Type="System.String" DbType="NChar(36)" CanBeNull="true" />
      <Column Name="F_userName" Type="System.String" DbType="VarChar(32)" CanBeNull="true" />
      <Column Name="F_pwd" Type="System.String" DbType="VarChar(32)" CanBeNull="true" />
      <Column Name="F_realName" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="F_sexual" Type="System.String" DbType="Char(2)" CanBeNull="true" />
      <Column Name="F_idType" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="F_idNumber" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="F_workDept" Type="System.String" DbType="NVarChar(40)" CanBeNull="true" />
      <Column Name="F_phone" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="F_mobile" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="F_highestDegree" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="F_highestEducation" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="F_nationality" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="F_birthday" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="F_position" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="F_title" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="F_freeAddress" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="F_phone2" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="F_fax" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="F_email" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="F_mostFamiliarSubject" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="F_familiarSubject1" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="F_familiarSubject2" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="F_Role" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="F_status" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="F_belongDeptID" Type="System.String" DbType="NChar(36)" CanBeNull="true" />
      <Column Name="F_bornplace" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="F_nativeplace" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="F_party" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="F_partyEntryDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="F_workBeginDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="F_highestGrduateSch" Type="System.String" DbType="NChar(30)" CanBeNull="true" />
      <Column Name="F_titleBeginDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="F_resume" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="F_rwdandpunishmt" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="F_lastModifyTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="F_posBeginDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="F_adminRanking" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="F_adminRkBeginDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.StaffFamilyMember" Member="StaffFamilyMember">
    <Type Name="StaffFamilyMember">
      <Column Name="F_MemID" Type="System.String" DbType="NChar(36) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="F_StaffID" Type="System.String" DbType="NChar(36)" CanBeNull="true" />
      <Column Name="F_familyMemName" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="F_familyMemBirthday" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="F_familyMemParty" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="F_familyMemWorkInfo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="F_familyMemAppelation" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.UpdateApplicant" Member="UpdateApplicant">
    <Type Name="UpdateApplicant">
      <Column Name="F_ID" Type="System.String" DbType="NChar(36) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="F_projectID" Type="System.String" DbType="NChar(36) NOT NULL" CanBeNull="false" />
      <Column Name="F_appliedDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="F_updateType" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="F_updateReason" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="F_beforeChange" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="F_beforeChangeAddition" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="F_afterChange" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="F_afterChangeAddition" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="F_status" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="F_statusEnum" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="F_schAuditOpinion" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="F_schAuditLeader" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="F_schAuditDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="F_eduAuditOpinion" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="F_eduAuditLeader" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="F_eduAuditDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Position" Member="Position">
    <Type Name="Position">
      <Column Name="F_ID" Type="System.String" DbType="NChar(36) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="F_posname" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="F_startDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="F_endDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="F_status" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="F_comment" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="F_code" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>